# Generated by Django 3.2.16 on 2022-12-01 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0006_boxsize'),
        ('flavours', '0002_delete_boxsize'),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(choices=[('Custom', 'Custom'), ('Pre Built', 'pre_built'), ('Pick and Mix', 'pick_and_mix')], max_length=30)),
                ('active', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('pre_build', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='flavours.prebuildflavour')),
                ('size', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='store.boxsize')),
            ],
        ),
    ]
