# Generated by Django 3.2.16 on 2022-12-04 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flavours', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoxSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.PositiveIntegerField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavour_format', models.CharField(choices=[('custom', 'Custom'), ('pre_built', 'Pre-Built'), ('pick_and_mix', 'Pick and Mix')], default='pre_built', max_length=30)),
                ('active', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('pre_built', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='flavours.prebuildflavour')),
                ('size', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='boxes.boxsize')),
            ],
        ),
    ]
