# Generated by Django 3.2.16 on 2022-12-01 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0002_auto_20221201_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='format',
            field=models.CharField(choices=[('Custom', 'custom'), ('Pre Built', 'pre_built'), ('Pick and Mix', 'pick_and_mix')], max_length=30),
        ),
    ]
