# Generated by Django 3.2.16 on 2022-12-02 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0003_alter_box_format'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box',
            name='format',
        ),
        migrations.AddField(
            model_name='box',
            name='flavour_format',
            field=models.CharField(choices=[('custom', 'custom'), ('pre_built', 'pre_built'), ('pick_and_mix', 'Pick and Mix')], default='pre_built', max_length=30),
        ),
    ]
