# Generated by Django 3.2.16 on 2022-12-13 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0003_boxsize_price_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxsize',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
