# Generated by Django 3.2.16 on 2022-12-14 10:54

import boxes.models
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0004_boxsize_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxsize',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=boxes.models.upload_location),
        ),
    ]
