# Generated by Django 3.2.16 on 2022-12-02 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0004_auto_20221202_1733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='box',
            old_name='pre_build',
            new_name='pre_built',
        ),
    ]
