# Generated by Django 3.2.16 on 2022-12-14 10:58

import boxes.models
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0005_boxsize_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxsize',
            name='image2',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=boxes.models.upload_location),
        ),
        migrations.AddField(
            model_name='boxsize',
            name='image3',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=boxes.models.upload_location),
        ),
        migrations.AddField(
            model_name='boxsize',
            name='image4',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=boxes.models.upload_location),
        ),
        migrations.AddField(
            model_name='boxsize',
            name='image5',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=boxes.models.upload_location),
        ),
    ]
