# Generated by Django 3.2.16 on 2022-12-14 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0006_auto_20221214_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxsize',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
