# Generated by Django 3.2.16 on 2022-12-17 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flavours', '0002_alter_flavour_options'),
        ('boxes', '0007_boxsize_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='selected_prebuilts',
            field=models.ManyToManyField(blank=True, related_name='selected_prebuilts', to='flavours.PreBuildFlavour'),
        ),
    ]
