# Generated by Django 3.2.16 on 2022-12-18 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flavours', '0003_flavourchoice'),
        ('boxes', '0008_box_selected_prebuilts'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='selected_flavours',
            field=models.ManyToManyField(blank=True, related_name='selected_flavours', to='flavours.FlavourChoice'),
        ),
    ]
