# Generated by Django 3.2.16 on 2022-12-19 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0009_box_selected_flavours'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxsize',
            name='color',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
