# Generated by Django 3.2.16 on 2022-12-19 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0010_boxsize_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boxsize',
            options={'ordering': ['size']},
        ),
    ]
