# Generated by Django 3.2.16 on 2023-01-02 20:47

import boxes.models
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0011_alter_boxsize_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxsize',
            name='store_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=boxes.models.upload_location),
        ),
    ]
