# Generated by Django 3.2.16 on 2023-03-14 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0012_boxsize_store_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxsize',
            name='custom_chocolates_min',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
