# Generated by Django 3.2.16 on 2023-03-17 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flavours', '0004_auto_20221219_0947'),
        ('custom_chocolates', '0008_alter_chocolatedesignbase_options'),
        ('boxes', '0013_boxsize_custom_chocolates_min'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='custom_chocolates_flavours',
            field=models.ManyToManyField(blank=True, null=True, to='flavours.Flavour'),
        ),
        migrations.AddField(
            model_name='box',
            name='custom_design',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='custom_chocolates.userchocolatedesign'),
        ),
    ]
