# Generated by Django 3.2.16 on 2023-07-05 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0016_auto_20230320_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxsize',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
