# Generated by Django 3.2.16 on 2023-07-12 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0017_boxsize_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxsize',
            name='seo_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='boxsize',
            name='seo_title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
