# Generated by Django 3.2.16 on 2023-09-26 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0019_boxsize_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxsize',
            name='special_box',
            field=models.BooleanField(default=False),
        ),
    ]
