# Generated by Django 3.2.16 on 2023-09-26 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0020_boxsize_special_box'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxsize',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
