# Generated by Django 3.2.16 on 2023-12-17 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0021_boxsize_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxsize',
            name='sold_out',
            field=models.BooleanField(default=False),
        ),
    ]
