# Generated by Django 3.2.16 on 2024-01-19 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0022_boxsize_sold_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxsize',
            name='valentines_box',
            field=models.BooleanField(default=False),
        ),
    ]
