# Generated by Django 3.2.16 on 2023-04-17 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0002_lot_custom_design'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='size',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
