# Generated by Django 3.2.16 on 2023-04-17 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0003_alter_lot_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lot',
            name='pre_built',
        ),
    ]
