# Generated by Django 3.2.16 on 2023-04-17 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0005_alter_lot_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lot',
            old_name='size',
            new_name='prebuilt_size',
        ),
    ]
