# Generated by Django 3.2.16 on 2023-04-17 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0006_rename_size_lot_prebuilt_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lot',
            old_name='price_stripe_id',
            new_name='price_stripe_id_1',
        ),
        migrations.AddField(
            model_name='lot',
            name='price_stripe_id_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lot',
            name='price_stripe_id_3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lot',
            name='price_stripe_id_4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
