# Generated by Django 3.2.16 on 2023-04-17 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0007_auto_20230417_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='LotPriceIds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('flavour_format', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='lot',
            name='price_stripe_id_1',
        ),
        migrations.RemoveField(
            model_name='lot',
            name='price_stripe_id_2',
        ),
        migrations.RemoveField(
            model_name='lot',
            name='price_stripe_id_3',
        ),
        migrations.RemoveField(
            model_name='lot',
            name='price_stripe_id_4',
        ),
    ]
