# Generated by Django 3.2.16 on 2023-04-17 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0008_auto_20230417_1417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lotpriceids',
            old_name='flavour_format',
            new_name='stripe_id',
        ),
    ]
