# Generated by Django 3.2.16 on 2023-04-17 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0009_rename_flavour_format_lotpriceids_stripe_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotpriceids',
            name='limit',
            field=models.PositiveIntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
