# Generated by Django 3.2.16 on 2022-12-04 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('street', models.CharField(max_length=120)),
                ('postal_code', models.CharField(max_length=5)),
                ('city', models.CharField(max_length=120)),
                ('tel', models.CharField(blank=True, max_length=120, null=True)),
                ('country', models.CharField(default='Mexico', max_length=120)),
                ('active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
