# Generated by Django 3.2.16 on 2022-12-24 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='address',
            name='full_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(max_length=500),
        ),
    ]
