# Generated by Django 3.2.16 on 2022-12-01 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20221201_2204'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PreBuildFlavours',
            new_name='PreBuildFlavour',
        ),
    ]
