# Generated by Django 3.2.16 on 2022-12-01 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_prebuildflavours_prebuildflavour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flavour',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='prebuildflavour',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
