# Generated by Django 3.2.16 on 2022-12-01 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20221201_2207'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BoxSize',
        ),
        migrations.DeleteModel(
            name='Flavour',
        ),
        migrations.DeleteModel(
            name='PreBuildFlavour',
        ),
    ]
