# Generated by Django 3.2.16 on 2022-12-01 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0002_auto_20221201_2239'),
        ('store', '0006_boxsize'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BoxSize',
        ),
    ]
