# Generated by Django 3.2.16 on 2023-07-05 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='discount_type',
        ),
        migrations.AddField(
            model_name='discount',
            name='is_percentage',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='max_uses',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='discount',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='stripe_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='discount',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
