# Generated by Django 3.2.16 on 2023-07-05 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0003_auto_20230705_1803'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discount',
            old_name='discount_type',
            new_name='type',
        ),
    ]
