# Generated by Django 3.2.16 on 2023-09-26 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0021_boxsize_name'),
        ('discounts', '0005_discount_box_exclusions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='box_exclusions',
        ),
        migrations.AddField(
            model_name='discount',
            name='box_exclusions',
            field=models.ManyToManyField(blank=True, related_name='box_exclusions', to='boxes.BoxSize'),
        ),
    ]
