# Generated by Django 3.2.16 on 2022-12-14 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartentry',
            name='total',
        ),
    ]
