# Generated by Django 3.2.16 on 2023-02-27 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_chocolates', '0005_auto_20230227_0207'),
        ('carts', '0002_remove_cartentry_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartentry',
            name='user_chocolate_design',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='custom_design', to='custom_chocolates.userchocolatedesign'),
        ),
    ]
