# Generated by Django 3.2.16 on 2023-07-05 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0003_auto_20230705_1803'),
        ('carts', '0003_cartentry_user_chocolate_design'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='discounts.discount'),
        ),
    ]
