# Generated by Django 3.2.16 on 2023-09-23 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
        ('carts', '0004_cart_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='shipping_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shipping.shippingtype'),
        ),
    ]
