# Generated by Django 3.2.16 on 2023-01-20 20:42

import custom_chocolates.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChocolateDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChocolateDesignLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('top_image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=custom_chocolates.models.upload_location)),
                ('side_image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=custom_chocolates.models.upload_location)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserChocolateDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('background', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='background', to='custom_chocolates.chocolatedesignlayer')),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='design', to='custom_chocolates.chocolatedesign')),
                ('layer1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='layer1', to='custom_chocolates.chocolatedesignlayer')),
                ('layer2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='layer2', to='custom_chocolates.chocolatedesignlayer')),
                ('layer3', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='layer3', to='custom_chocolates.chocolatedesignlayer')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='chocolatedesign',
            name='background_options',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='background_options', to='custom_chocolates.chocolatedesignlayer'),
        ),
        migrations.AddField(
            model_name='chocolatedesign',
            name='layer1_options',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='layer1_options', to='custom_chocolates.chocolatedesignlayer'),
        ),
        migrations.AddField(
            model_name='chocolatedesign',
            name='layer2_options',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='layer2_options', to='custom_chocolates.chocolatedesignlayer'),
        ),
        migrations.AddField(
            model_name='chocolatedesign',
            name='layer3_options',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='layer3_options', to='custom_chocolates.chocolatedesignlayer'),
        ),
    ]
