# Generated by Django 3.2.16 on 2023-01-20 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_chocolates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chocolatedesign',
            name='title',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='chocolatedesignlayer',
            name='title',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
