# Generated by Django 3.2.16 on 2023-01-20 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_chocolates', '0003_auto_20230120_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chocolatedesign',
            name='background_options',
            field=models.ManyToManyField(blank=True, related_name='background_options', to='custom_chocolates.ChocolateDesignLayer'),
        ),
        migrations.AlterField(
            model_name='chocolatedesign',
            name='layer1_options',
            field=models.ManyToManyField(blank=True, related_name='layer1_options', to='custom_chocolates.ChocolateDesignLayer'),
        ),
        migrations.AlterField(
            model_name='chocolatedesign',
            name='layer2_options',
            field=models.ManyToManyField(blank=True, related_name='layer2_options', to='custom_chocolates.ChocolateDesignLayer'),
        ),
        migrations.AlterField(
            model_name='chocolatedesign',
            name='layer3_options',
            field=models.ManyToManyField(blank=True, related_name='layer3_options', to='custom_chocolates.ChocolateDesignLayer'),
        ),
    ]
