# Generated by Django 3.2.16 on 2023-02-27 02:07

import custom_chocolates.models
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('custom_chocolates', '0004_auto_20230120_2102'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChocolateDesignBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120, null=True)),
                ('top_image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=custom_chocolates.models.upload_location)),
                ('side_image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=custom_chocolates.models.upload_location)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChocolateDesignLayerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='chocolatedesign',
            name='background_options',
        ),
        migrations.RemoveField(
            model_name='userchocolatedesign',
            name='background',
        ),
        migrations.AddField(
            model_name='chocolatedesign',
            name='layer1_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='chocolatedesign',
            name='layer2_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chocolatedesign',
            name='layer2_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='chocolatedesign',
            name='layer3_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chocolatedesign',
            name='layer3_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='chocolatedesign',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='userchocolatedesign',
            name='layer2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='layer2', to='custom_chocolates.chocolatedesignlayer'),
        ),
        migrations.AlterField(
            model_name='userchocolatedesign',
            name='layer3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='layer3', to='custom_chocolates.chocolatedesignlayer'),
        ),
        migrations.AddField(
            model_name='chocolatedesign',
            name='base_options',
            field=models.ManyToManyField(blank=True, related_name='base_options', to='custom_chocolates.ChocolateDesignBase'),
        ),
        migrations.AddField(
            model_name='userchocolatedesign',
            name='base',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='base', to='custom_chocolates.chocolatedesignbase'),
        ),
    ]
