# Generated by Django 3.2.16 on 2023-02-27 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_chocolates', '0005_auto_20230227_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='chocolatedesignlayer',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='type', to='custom_chocolates.chocolatedesignlayertype'),
        ),
    ]
