# Generated by Django 3.2.16 on 2023-03-07 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_chocolates', '0006_chocolatedesignlayer_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='LayerColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.AlterModelOptions(
            name='chocolatedesign',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='chocolatedesignbase',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='chocolatedesignlayer',
            options={'ordering': ['type', 'color']},
        ),
        migrations.AlterModelOptions(
            name='chocolatedesignlayertype',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='userchocolatedesign',
            options={'ordering': ['timestamp']},
        ),
        migrations.AddField(
            model_name='chocolatedesignbase',
            name='base_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='base_color', to='custom_chocolates.layercolor'),
        ),
        migrations.AddField(
            model_name='chocolatedesignlayer',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='color', to='custom_chocolates.layercolor'),
        ),
    ]
