# Generated by Django 3.2.16 on 2023-03-14 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_chocolates', '0007_auto_20230307_1210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chocolatedesignbase',
            options={'ordering': ['base_color']},
        ),
    ]
