# Generated by Django 3.2.16 on 2023-03-20 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_chocolates', '0008_alter_chocolatedesignbase_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchocolatedesign',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
