# Generated by Django 3.2.16 on 2023-04-12 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_chocolates', '0009_userchocolatedesign_featured'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userchocolatedesign',
            options={'ordering': ['-timestamp']},
        ),
    ]
