# Generated by Django 3.2.16 on 2022-12-14 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flavours', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flavour',
            options={'ordering': ['name']},
        ),
    ]
