# Generated by Django 3.2.16 on 2022-12-18 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flavours', '0002_alter_flavour_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlavourChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('flavour', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='flavours.flavour')),
            ],
        ),
    ]
