# Generated by Django 3.2.16 on 2022-12-19 09:47

from django.db import migrations, models
import flavours.models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('flavours', '0003_flavourchoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='flavour',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flavour',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=flavours.models.upload_location),
        ),
        migrations.AddField(
            model_name='flavour',
            name='allergens',
            field=models.ManyToManyField(blank=True, to='flavours.Allergen'),
        ),
    ]
