# Generated by Django 3.2.16 on 2023-07-03 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flavours', '0004_auto_20221219_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='flavour',
            name='mini_description',
            field=models.TextField(blank=True, max_length=80, null=True),
        ),
    ]
