# Generated by Django 3.2.16 on 2022-12-17 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_shipping_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipping_cost',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
    ]
