# Generated by Django 3.2.16 on 2022-12-19 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20221217_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(null=True, verbose_name='Delivery Date'),
        ),
    ]
