# Generated by Django 3.2.16 on 2022-12-19 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_delivery_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_date',
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_date',
            field=models.DateField(null=True, verbose_name='Shipping Date'),
        ),
    ]
