# Generated by Django 3.2.16 on 2023-01-20 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20221219_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('created', 'created'), ('cancelled', 'cancelled'), ('delivered', 'delivered')], default='created', max_length=120),
        ),
    ]
