# Generated by Django 3.2.16 on 2024-01-25 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20240125_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='visited_pages',
            field=models.TextField(blank=True, null=True),
        ),
    ]
