# Generated by Django 3.2.16 on 2024-03-17 11:45

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weight', models.PositiveIntegerField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('price_id', models.CharField(blank=True, max_length=200, null=True)),
                ('custom_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('custom_price_id', models.CharField(blank=True, max_length=200, null=True)),
                ('active', models.BooleanField(default=True)),
                ('sold_out', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True)),
                ('seo_title', models.CharField(blank=True, max_length=200)),
                ('seo_description', models.TextField(blank=True)),
                ('store_image', models.ImageField(blank=True, null=True, upload_to=products.models.upload_location)),
                ('image', models.ImageField(blank=True, null=True, upload_to=products.models.upload_location)),
                ('image2', models.ImageField(blank=True, null=True, upload_to=products.models.upload_location)),
                ('image3', models.ImageField(blank=True, null=True, upload_to=products.models.upload_location)),
                ('image4', models.ImageField(blank=True, null=True, upload_to=products.models.upload_location)),
                ('image5', models.ImageField(blank=True, null=True, upload_to=products.models.upload_location)),
            ],
        ),
    ]
