# Generated by Django 3.2.16 on 2024-03-17 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('general', 'General'), ('snacks', 'Snacks')], default='snacks', max_length=20),
            preserve_default=False,
        ),
    ]
